import React from 'react';
import { motion } from 'framer-motion';

const About = () => {
    return (
        <div className="about-page" style={{ paddingTop: '100px', background: 'var(--light)' }}>
            {/* Hero Section */}
            <section className="section" style={{ padding: '6rem 5%', textAlign: 'center' }}>
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                >
                    <span style={{
                        color: 'var(--primary)',
                        fontWeight: 800,
                        textTransform: 'uppercase',
                        letterSpacing: '2px',
                        fontSize: 'var(--font-sm)',
                        display: 'block',
                        marginBottom: '1rem'
                    }}>Our Core Mission</span>
                    <h1 style={{
                        fontSize: 'clamp(2.5rem, 8vw, 4.5rem)',
                        fontWeight: 900,
                        lineHeight: 1.1,
                        background: 'linear-gradient(to bottom, var(--dark), #4b5563)',
                        WebkitBackgroundClip: 'text',
                        WebkitTextFillColor: 'transparent',
                        marginBottom: '1.5rem'
                    }}>
                        Giving Premium Gadgets <br />
                        <span style={{ color: 'var(--primary)', WebkitTextFillColor: 'initial' }}>A Second Life.</span>
                    </h1>
                    <p style={{
                        maxWidth: '800px',
                        margin: '0 auto',
                        fontSize: '1.25rem',
                        color: 'var(--gray)',
                        lineHeight: 1.8
                    }}>
                        RefurbNest was born from a simple idea: flagship technology shouldn't cost the earth.
                        We're on a mission to reduce carbon footprints while making elite hardware
                        accessible through our rigorous 49-point certification engine.
                    </p>
                </motion.div>
            </section>

            {/* Values Grid */}
            <section className="section" style={{ background: 'var(--white)', padding: '8rem 5%', borderRadius: '48px 48px 0 0', boxShadow: '0 -20px 40px rgba(0,0,0,0.02)' }}>
                <div style={{
                    display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
                    gap: '2.5rem'
                }}>
                    <AboutCard
                        title="Certified Quality"
                        desc="Every device undergoes a 49-point diagnostic test by our expert engineers to ensure like-new performance."
                        icon="🛠️"
                    />
                    <AboutCard
                        title="Eco-Innovation"
                        desc="Choosing refurbished prevents up to 80% of the electronic waste generated by manufacturing new devices."
                        icon="🌱"
                    />
                    <AboutCard
                        title="Ironclad Support"
                        desc="We stand by our work. Every purchase includes a comprehensive 6-month doorstep warranty for peace of mind."
                        icon="🛡️"
                    />
                </div>
            </section>
        </div>
    );
};

const AboutCard = ({ title, desc, icon }) => (
    <motion.div
        whileHover={{ y: -10 }}
        style={{
            padding: '3.5rem 2.5rem',
            borderRadius: 'var(--radius-xl)',
            background: 'var(--light)',
            border: '1px solid #f1f5f9',
            position: 'relative',
            overflow: 'hidden'
        }}
    >
        <div style={{ fontSize: '3rem', marginBottom: '1.5rem' }}>{icon}</div>
        <h3 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '1.2rem', color: 'var(--dark)' }}>{title}</h3>
        <p style={{ color: 'var(--gray)', fontSize: '1.1rem', lineHeight: 1.6 }}>{desc}</p>

        {/* Subtle accent line */}
        <div style={{
            position: 'absolute',
            bottom: 0,
            left: 0,
            width: '100%',
            height: '4px',
            background: 'linear-gradient(to right, transparent, var(--primary), transparent)'
        }}></div>
    </motion.div>
);

export default About;
